apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: health
  selector:
    app: rabbitmq
