FROM openjdk:oracle
ENV MODEL_URL http://172.17.0.4:80
ENV FRONT_URL http://172.17.0.3
ENV RABBITMQ_URL rabbitmq
ENV DATASOURCE_URL jdbc:postgresql://172.17.0.2:5432/postgres
ENV DATASOURCE_USERNAME postgres
ENV DATASOURCE_PASSWORD postgres
ADD target/maioop-0.0.1-SNAPSHOT.jar /
EXPOSE 8080
CMD ["java", "-jar", "maioop-0.0.1-SNAPSHOT.jar"]