apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: back
spec:
  selector:
    matchLabels:
      app: back
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: back
    spec:
      nodeSelector:
        size: small
      containers:
        - image: dazz1ee/backend
          imagePullPolicy: Always
          name: back
          env:
            - name: MODEL_URL
              value: "http://ml"
            - name: FRONT_URL
              value: "http://"
          ports:
            - containerPort: 8080